spring:
  profiles:
    active: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://193.112.102.134:3306/wexinmap?verifyServerCertificate=false&useSSL=true&characterEncoding=gbk
      username: root
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /

  port: 8443
  ssl:

      key-store: classpath:shaqianqian.xyz.jks
      key-store-password: 768hn6mn4ikh3
      key-store-type: JKS

